model_dir: output/caption/26_04_04_05_42_59
llm_name: llm
projector_name: projector.pt
image_path: null
eval_image_path: data/Flicker8k_Dataset
eval_text_path: data/Flickr8k.token.txt
eval_split_path: data/Flickr_8k.testImages.txt
max_new_tokens: 32
output_path: output/caption/26_04_04_05_42_59/eval_results.json
